apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-jedi
  labels:
    app: devops-jedi
  annotations:
spec:
  selector:
    matchLabels:
      app: devops-jedi
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: devops-jedi
    spec:
      containers:
      - name: devops-jedi
        image: tomasmortensenscb/devops-jedi-web:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets/
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: secret-volume
        secret:
          secretName: mysecret
      - name: config-volume
        configMap:
          name: devops-jedi-config #name of our configmap object